### ISSUE TITLE
NSAssert compiler errors

### ISSUE THREAD

**Issue by kgn** [roddi/ValidateStoreReceipt#11]
The new NSAssert lines are failing for me with the compiler errors:

Use of undeclared identifier '_cmd'; did you mean 'rcmd'?
Use of undeclared identifier 'self'

**Comment by ghost** [comment]
I received the same errors. I fixed it by changing the code to:

```
NSCAssert([bundleVersion isEqualToString:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"]], 
         @"whoops! check the hard-coded CFBundleShortVersionString!");
NSCAssert([bundleIdentifer isEqualToString:[[NSBundle mainBundle] bundleIdentifier]], 
         @"whoops! check the hard-coded bundle identifier!");
```

**Comment by kgn** [comment]
Awesome thanks!

**Comment by Nonnus** [comment]
just had same problem here,
nice post but shouldnt this changes be already commited to repo ?

**Comment by roddi** [comment]
Committed. Thanks!
