### ISSUE TITLE
wont compile in project

### ISSUE THREAD

**Issue by kilabyte** [roddi/ValidateStoreReceipt#12]
ok so i have added the xcodeproject file to my testproject, i added the dependencies under the target info i have added all the frameworks, modified my main, and still i'm getting 36 errors of (here is one...)

"_BIO_new", referenced from: _dictionaryWithAppStoreReceipt in validatereceipt.o

no clue

**Comment by kilabyte** [comment]
any idea on what i'm doing wrong?

**Comment by kgn** [comment]
I think the problem might be that you don't want to add the xcodeproject to your project. You just need to add validatereceipt.h and validatereceipt.m to your project.

**Comment by kilabyte** [comment]
Nope... i get the same 36 errors... :S

**Comment by kgn** [comment]
Did you add add libCrypto to the build settings? This step is different then how the other dependencies are added: "libCrypto (via -lcrypto in Other Linker Flags)".

**Comment by kilabyte** [comment]
Awesome! Done! maybe we should document this for other users?

Thanks so much for you help!

**Comment by kgn** [comment]
Glad that worked!

This is in the docs already, the Installation section of the README says to link with the dependencies listed in validatereceipt.m, which refers to this line:

// link with Foundation.framework, IOKit.framework, Security.framework and libCrypto (via -lcrypto in Other Linker Flags)

**Comment by kilabyte** [comment]
gotcha! i had the other frameworks linked just didn't see that line. again thanks so much!
