### ISSUE TITLE
Memory leaks in CRYPTO_malloc (malloc of 32 bytes being lost)

### ISSUE THREAD

**Issue by GerTeunis** [roddi/ValidateStoreReceipt#2]
After some leak profiling the profiler reports a lot of memory leaks in CRYTO_malloc.

Leaked Object   #   Address Size    Responsible Library Responsible Frame
Malloc 32 Bytes 7   < multiple >    224 Bytes   libcrypto.0.9.7.dylib   CRYPTO_malloc

**Comment by roddi** [comment]
Sounds like a newer OpenSSL lib crypto would help. Up to you to figure out how to do that in your project
