### ISSUE TITLE
Helpful code if you are trying to validate a real receipt

### ISSUE THREAD

**Issue by ghost** [roddi/ValidateStoreReceipt#6]
In order to validate against the real receipt after testing, change this line of code:

`if (!validateReceiptAtPath(@"~/Desktop/receipt"))`

to

`NSString *pathToReceipt = [[[NSBundle mainBundle] bundlePath]   stringByAppendingPathComponent:@"Contents/_MASReceipt/receipt"];`

`if (!validateReceiptAtPath(pathToReceipt))`

`exit(173);//receipt did not validate`

courtesy http://jesusagora.org/groups/futurebasic/0::53562:get:1read.html

**Comment by roddi** [comment]
Correct. Won't fix, as everyone has to do that in their own code
